version: '2.3'

services:
    lb:
        image: dockercloud/haproxy
        ports:
          - '5672:5672'
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        environment:
          - TIMEOUT=connect 5000, client 0, server 0
        links:
          - rabbitmq

    rabbitmq-master:
        hostname: rabbitmq-master
        image: rabbitmq-cluster:3.7.5-rc.1
        environment:
          - RABBITMQ_DEFAULT_USER=admin
          - RABBITMQ_DEFAULT_PASS=admin
          - ERLANG_COOKIE=SOMETHING_BLAH_BLAH_SECURE
        ports:
          - "15672:15672"
        expose:
            - "5672"
            - "25672"
            - "4369"
            - "9100"
            - "9101"
            - "9102"
            - "9103"
            - "9104"
            - "9105"
    rabbitmq:
        image: rabbitmq-cluster:3.7.5-rc.1
        scale: 4
        environment:
          - CLUSTER_WITH=rabbitmq-master
          - TCP_PORTS=5672
          - ERLANG_COOKIE=SOMETHING_BLAH_BLAH_SECURE
        expose:
            - "5672"
            - "25672"
            - "4369"
            - "9100"
            - "9101"
            - "9102"
            - "9103"
            - "9104"
            - "9105"
